version: "3"

services:
  car-prediction-dashboard: 
    build: 
      context: ./dashboard 
    container_name: car-prediction-dashboard 
    expose: 
      - 8000 
    ports: 
      - 8033:8000 
  car-prediction: 
    build: 
      context: ./prediction 
    container_name: car-prediction 
    expose:
      - 80 
    ports: 
      - 8032:80 
    